### ISSUE TITLE
BTCN model missing

### ISSUE THREAD

**Issue by raopx** [CPJKU/madmom_models#16]
`BEATS_BTCN = models('beats/2019/beats_btcn_[1-8].pkl') ` mapping missing in beats model directory.

**Comment by superbock** [comment]
Yes, they are still missing. Basically everything is ready, but there's still one issue that needs to be resolved. Since there's no dilated convolution in numpy/scipy/opencv there are two options: i) spread the kernel and fill with zeros, or ii) use the correct part of the signal and convolve it as normal. Unfortunately, I chose i) for my reference implementation which leads to bloated models — which I do not want to be included in the repository. Possible solutions are either use option ii), use sparse matrices, or compress them. Even more unfortunately I have quite limited time for things like this right now, but it is very high on my todo list.
